import { useEffect } from 'react'
import Head from 'next/head'
import Page from '../components/templates/Page'
import { motion } from "framer-motion"
import axios from 'axios'
import { useSession } from 'next-auth/react'
import { setCookies } from 'cookies-next'

export async function getServerSideProps({ req }) {
  const secure = req.connection.encrypted
  const url = `${secure ? "https" : "http"}://${req.headers.host}/api/products`
  const res = await axios.get(url)

  return {
    props: {
      products: res.data
    }
  }
}

export default function Home({ products }) {
  const { data: session } = useSession()
  
  if (session?.user?.id) {
    console.log("Session",  session)
    setCookies("userID", session.user?.id)
    setCookies("email", session.user?.email)
  }

  useEffect(()=>{
    console.log('data session', session)
    console.log('products', products)
  },[])

  return (
    <section>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-full bg-slate-50 dark:bg-palette-dark-darker'>
        <h1 className='text-black dark:text-white'>Hola soy un Texto</h1>
        <div className='w-[100px] h-[100px] dark:bg-palette-dark-black'>

        </div>
      </div>
    </section>
  )
}
